#!/bin/sh
export DWMSTATUS_DIR=${HOME}/Projects/gdsb
while :; do
    echo "$(cat /sys/class/power_supply/BAT0/capacity)" > ${HOME}/.cache/gdsb_battery
    . ${DWMSTATUS_DIR}/update
    sleep 1m
done
